name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Typecheck
        run: yarn tsc
      - name: Test
        run: yarn test:all
      - name: Report Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/coverage-final.json
      - name: Format
        run: yarn prettier:check
      - name: Build
        run: yarn build:all
      - name: Changeset
        run: yarn changeset status --since origin/main
        if: ${{ github.ref_name != 'main' }}
